import type { Metadata } from 'next'
import { Podkova } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const podkova = Podkova({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='bg-cyan-50'>
      <body className={podkova.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
